baseURL: "https://beyondlines.netlify.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Beyond Lines"

# googleAnalytics: ""

summaryLength: 20
enableEmoji: true


params:
  title: "Web Marketing"
  description: "Planning, innovating & analyzing your social media to help grow your business"
  images: 
    - "images/LOGO5.png"

  logo: "images/LOGO5.png"

  favicons:
    themeColor: "#484e68"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "https://www.instagram.com/beyondlines_digital/"
    facebook: "https://www.facebook.com/profile.php?id=100085933003386"
    twitter: "#"

  location:
    - "Toronto, ON"


  contact:
    - "beyondlinesdigital@gmail.com"
    

  copyright: "© 2022 Up Business All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/post/procedures"
      weight: 2

    - name: "Pricing"
      url: "/post/pricing"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a Appoitment"
      url: "https://www.instagram.com/beyondlines_digital/"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/post/procedures"
      weight: 2

    - name: "Pricing"
      url: "/post/pricing"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
